version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Release

before_build:
    - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    - mkdir build

build_script:
    - cd build
    - cmake ..
    - cmake --build .

