language: cpp

sudo: false

#compiler:
#    - gcc
#    - clang

os:
    - linux
    - osx

install:
    - git submodule update --init --recursive

before_script:
    - mkdir build

script:
    - cd build
    - cmake ..
    - cmake --build .
    - ctest

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

