language: cpp

sudo: false

compiler:
    - gcc

os:
    - linux

install:
    - git submodule update --init --recursive

before_script:
    - mkdir build

script:
    - cd build
    - cmake ..
    - cmake --build .
    - ctest

addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - cmake-data
            - g++-6

env: COMPILER=g++-6

