language: cpp

sudo: false

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

install:
    - git submodule update --init --recursive

before_script:
    - mkdir build

script:
    - cd build
    - cmake ..
    - cmake --build .
    - ctest

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data

