language: cpp
sudo: false

os: linux

cache:
    apt: true
    directories:
        - external

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build

script:
    - cd build
    - cmake ..
    - cmake --build .
#    - ctest

addons:
    apt:
        sources: &global_apt_sources
            - george-edison55-precise-backports
        packages: &global_apt_packages
            - cmake
            - cmake-data

matrix:
    include:
        - compiler: gcc
          env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
          addons:
              apt:
                  sources:
                      - *global_apt_sources
                      - ubuntu-toolchain-r-test
                  packages:
                      - *global_apt_packages
                      - g++-5
        - compiler: gcc
          env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
          addons:
              apt:
                  sources:
                      - *global_apt_sources
                      - ubuntu-toolchain-r-test
                  packages:
                      - *global_apt_packages
                      - g++-6

